config/routes.rb
Rails.application.routes.draw do
  resources :participations
  resources :events do
    collection do
      post 'filter_events_by_genre'
    end
  end
  get 'home/index'
  root to: 'genres#index'
  get '/auth/:provider/callback', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  post 'participate_to_event/:id', to:'events#participate'

  get  'my_events', to: 'events#display_events_map'
  get  'events_list', to: 'events#fetch_my_events'

  resources :genres, only: [:index]
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  class << self
    def add_participation(event_id,participant_id)
      participation = find_or_create_by(event_id: event_id, participant_id: participant_id)
      participation.save!
      participation
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.name = auth_hash['info']['name']
      user.location = auth_hash['info']['location']
      user.image_url = auth_hash['info']['image']
      user.url = auth_hash['info']['urls'][user.provider.capitalize]
      user.save!
      user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy,:participate]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def filter_events_by_genre
    chosen_genre = Genre.where({name: params[:genres]})
    @filtered_events = Event.where({genre_id: chosen_genre.pluck(:name)})
  end

  def display_events_map    
	render :my_events
  end

  def participate
    participation = Participation.find_or_create_by(event_id: @event.id, participant_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'You are successfully registered for the event' }
      format.json { head :no_content }
    end
  end

  def fetch_my_events
  	participations = Participation.where(participant_id: current_user.id)
  	event_ids = participations.map{|participation| participation.event_id};
  	@my_events = Event.where(id: event_ids).to_json;
  	respond_to do |format|	
	  format.json { render json: @my_events }
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :venue_latitude, :venue_logitude, :genre_id, :description)
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create
    @participation = Participation.new(participation_params)

    respond_to do |format|
      if @participation.save
        format.html { redirect_to @participation, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: 'Participation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.require(:participation).permit(:event_id, :participant_id)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    # render text: request.env['omniauth.auth'].to_yaml
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end
    redirect_to root_path
  end
  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
  def all_genres
    @genres.collect { |genre| genre.name }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :venue_latitude %><br>
    <%= f.text_field :venue_latitude %>
  </div>
  <div class="field">
    <%= f.label :venue_logitude %><br>
    <%= f.text_field :venue_logitude %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.text_field :genre_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :organizer_phone_number %><br>
    <%= f.text_field :organizer_phone %>
  </div>

    <div class="field">
      <%= f.label :organizer_email %><br>
      <%= f.text_field :organizer_email %>
    </div>
    <div class="field">
      <%= hidden_field_tag :organizer_id, current_user.id %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', root_path %>

app/views/events/filter_events_by_genre.html.erb
<% @filtered_events.each do |event| -%>
    <div class="card">
      <%= link_to event_path(event.id), class: 'card1' do %>
          <div class="textLeft card-text"><%= event.title %> </div>
      <% end %>
      <div class="event-description">
        <%= event.description %>
      </div>
    </div>
<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Venue latitude</th>
      <th>Venue logitude</th>
      <th>Genre</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.venue_latitude %></td>
        <td><%= event.venue_logitude %></td>
        <td><%= event.genre_id %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/my_events.html.erb
 <div id="eventsmap">
 	
 </div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/events/show.html.erb
<div class="container">
    <div class="alert alert-info text-center">
      <h1> <%= @event.title %>   <span class="label label-default"><%= @event.genre_id %></span></h1>
    </div>
    <div class="text-center">
      <span class="fa fa-bold fa-calendar icon-bold"></span>
      <span class="bold"><%= @event.date %></span>
    </div>
  <div class="text-center row">
    <%= @event.description %>
  </div>
  <div class="text-center row">
    <span class="fa fa-bold fa-mobile"> <%= @event.organizer_phone %></span>
  </div>

  <div> Organized by :
    <span class="text-center"> <%= User.find(@event.organizer_id).name %></span>
    <%= image_tag User.find(@event.organizer_id).image_url, alt: User.find(@event.organizer_id).name %>
  </div>

</div>

<%= button_to 'Participate to event', action: :participate, id: @event.id %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', root_path %>

app/views/genres/index.html.erb
<div class="search-genres">
  <%= form_tag filter_events_by_genre_events_path, {id: 'search-genre-form'} do %>
      <%= select_tag 'genres',
                     options_for_select(all_genres),
                     include_blank: true,
                     class: 'chosen-select genres-name',
                     data: {placeholder: 'Select a genre'}
      %>
      <%= button_tag 'Search events', class: 'btn btn-success search-button' %>
  <% end %>
</div>

app/views/home/index.html.erb
<% if current_user %>
    <div class="page-header">
      <h1>Here is some info about you...</h1>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <ul>
          <li><strong>Name:</strong> <%= current_user.name %></li>
          <li><strong>Provider:</strong> <%= current_user.provider %></li>
          <li><strong>uID:</strong> <%= current_user.uid %></li>
          <li><strong>Location:</strong> <%= current_user.location %></li>
          <li><strong>Avatar URL:</strong> <%= current_user.image_url %></li>
          <li><strong>URL:</strong> <%= current_user.url %></li>
        </ul>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MistressGumpu</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css"/>
  <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.15.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.15.0/mapbox-gl.css' rel='stylesheet'/>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", :border => 0), root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <% if current_user %>
          <ul class="nav navbar-nav pull-right">
            <li><%= image_tag current_user.image_url, alt: current_user.name %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
            <li><%= link_to 'My Events', my_events_path, id: "my_events_nav_item", class: "my_events_nav_item", method: :get %></li>
            <li><%= link_to 'Add a new Event', new_event_path, id: "my_events_nav_item1", class: "my_events_nav_item1", method: :get %></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Google+', '/auth/google_oauth2' %></li>
          </ul>
      <% end %>
    </div>
    <div class="divider"></div>
    <%= yield %>
  </div>
</nav>
</body>
</html>

app/views/participations/_form.html.erb
<%= form_for(@participation) do |f| %>
  <% if @participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% @participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :participant_id %><br>
    <%= f.text_field :participant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participations/edit.html.erb
<h1>Editing Participation</h1>

<%= render 'form' %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participations</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Participant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= participation.event_id %></td>
        <td><%= participation.participant_id %></td>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participation', new_participation_path %>

app/views/participations/new.html.erb
<h1>New Participation</h1>

<%= render 'form' %>

<%= link_to 'Back', participations_path %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @participation.event_id %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @participation.participant_id %>
</p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>